name: WordPress CI/CD Pipeline

on:
  schedule:
    - cron: "0 0 * * *"  # This runs every day at midnight UTC (adjust to your timezone)
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and deploy WordPress container
      run: |
        docker-compose down
        docker-compose up -d
        docker ps
